name: CI
on:
  push:
    branches:
        - master
        - main
jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH Commands
            # You may pin to the exact commit or the version.
            # uses: fifsky/ssh-action@58b3c484be9c20cf118fd3b939a6d2cb3c769512
        uses: fifsky/ssh-action@v0.0.6
        with:
            command: |
                    cd Rust-Wordle-Api
                    ls
                    docker-compose down
                    git pull
                    git status
                    docker-compose up --build -d
                    
            host: ${{ secrets.DEPLOY_SSH_HOST }}
            user: ${{ secrets.DEPLOY_SSH_USER }}
            key:  ${{ secrets.DEPLOY_SSH_KEY }}
